-------------------------------------------------------------------------------
Test set: rest.RenameMeResourceTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.036 s <<< FAILURE! - in rest.RenameMeResourceTest
rest.RenameMeResourceTest  Time elapsed: 8.036 s  <<< ERROR!
javax.persistence.PersistenceException: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
	at rest.RenameMeResourceTest.setUpClass(RenameMeResourceTest.java:44)
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 

Internal Exception: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
	at rest.RenameMeResourceTest.setUpClass(RenameMeResourceTest.java:44)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at rest.RenameMeResourceTest.setUpClass(RenameMeResourceTest.java:44)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at rest.RenameMeResourceTest.setUpClass(RenameMeResourceTest.java:44)
Caused by: java.net.ConnectException: Connection refused: connect
	at rest.RenameMeResourceTest.setUpClass(RenameMeResourceTest.java:44)

